### ISSUE TITLE
Issue using i3-grid with latest rev of i3gridrc

### ISSUE THREAD

**Issue by jsalk** [justahuman1/i3-grid#4]
I'm not sure where the missing punctuation is that's causing this error, as I'm woefully out of touch with any type of coding.  But something in this move breaks things.  If I revert to the older variant(s) of the i3gridrc things work just fine.

jsalk@nemesis: ~/.config/i3grid $ python3 -m i3grid center                                                [15:42:45]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/i3grid/__main__.py", line 55, in <module>
    manager = FloatManager(commands=comx, **args.__dict__,)
  File "/usr/lib/python3.8/site-packages/i3grid/grid.py", line 693, in __init__
    Utils.read_config()
  File "/usr/lib/python3.8/site-packages/i3grid/grid.py", line 260, in read_config
    config = yaml.safe_load(f)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 549, in parse_flow_mapping_key
    raise ParserError("while parsing a flow mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a flow mapping
  in "/home/jsalk/.config/i3grid/i3gridrc", line 1, column 1
expected ',' or '}', but got ':'
  in "/home/jsalk/.config/i3grid/i3gridrc", line 7, column 24

**Comment by justahuman1** [comment]
Hi, apologies for this issue. For now, please continue to use the old rc file. I was waiting for someone to test the new rc file and parser.

Your current bug is because:
1. You downloaded from either pip or AUR (the code was structured for the old rc file)
2. You curled the new rc file format

The code in the repo is updated but I have not pushed the changes to pip/AUR. I will do that within the hour. Moving forward, I will upload the tests into a different branch (should have done so for this as well).

Thanks for this issue and I applaud the debugging skills to curl the old rc file. I will update this as a bug until I push out the newest build.

Changing to the newest rc file should be a minor change from the users end.

**Comment by justahuman1** [comment]
Hi, the newest builds have been pushed out. You may upgrade your build correspondingly:

```
# if downloaded through pip
pip install --upgrade i3-grid

# if AUR
yay -S python-i3-grid

# updating rc file
curl https://raw.githubusercontent.com/justahuman1/i3-grid/master/.i3gridrc > ~/.config/i3grid/i3gridrc
```

Let me know if this fixes it for you and I will close the issue. Thanks.

**Comment by jsalk** [comment]
Only curl'ing the updated RC file did not resolve the issue.  Removing and reinstalling from AUR however did.

Issue is resolved, close away.  And thanks for the work
