### ISSUE TITLE
KeyErrors on workspace numbers

### ISSUE THREAD

**Issue by cpebble** [justahuman1/i3-grid#7]
This has started to pop up in my workflow. I3grid has completely stopped working, with the following traceback:

```
>>= python -m i3grid center
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/i3grid/__main__.py", line 60, in <module>
    manager = FloatManager(commands=comx, **args.__dict__,)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/i3grid/grid.py", line 700, in __init__
    self.post_commands(all_key=self._TERMSIG)  # Sync to state
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/i3grid/grid.py", line 767, in post_commands
    self.area_matrix[self.workspace_num],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 2
```

This counts for every workspace and i3grid both from aur and pip

**Comment by grimnight** [comment]
Just got this to work, with a quick hack. Probably could have been better code.

Just replace this code:
```python
        if not self.cache_grid:
            self.float_grid = self.calculate_grid(
                BASE_CONFIG["defaultGrid"]["rows"],
                BASE_CONFIG["defaultGrid"]["columns"],
                self.area_matrix[self.workspace_num],
            )
```

With this code:
```python
        current = [ws for ws in i3.get_workspaces() if ws['focused']][0]
        if not self.cache_grid:
            self.float_grid = self.calculate_grid(
                BASE_CONFIG["defaultGrid"]["rows"],
                BASE_CONFIG["defaultGrid"]["columns"],
                self.area_matrix[int(current['name'])],
            )
```
In `post_commands` function.

**Comment by grimnight** [comment]
> Just got this to work, with a quick hack. Probably could have been better code.
> 
> Just replace this code:
> 
> ```python
>         if not self.cache_grid:
>             self.float_grid = self.calculate_grid(
>                 BASE_CONFIG["defaultGrid"]["rows"],
>                 BASE_CONFIG["defaultGrid"]["columns"],
>                 self.area_matrix[self.workspace_num],
>             )
> ```
> 
> With this code:
> 
> ```python
>         current = [ws for ws in i3.get_workspaces() if ws['focused']][0]
>         if not self.cache_grid:
>             self.float_grid = self.calculate_grid(
>                 BASE_CONFIG["defaultGrid"]["rows"],
>                 BASE_CONFIG["defaultGrid"]["columns"],
>                 self.area_matrix[int(current['name'])],
>             )
> ```
> 
> In `post_commands` function.

Turns out I was too hasty with my reply.

Now it should work, I hope:
```python
        workspaces = i3.get_workspaces()
        focused_workspace = [w for w in workspaces if w['focused']][0]
        focused_output = focused_workspace['output']
        current_outputs = i3.get_outputs()
        current_output_tmp = [w for w in current_outputs if w['name'] != "xroot-0"]
        current_output_index = next((index for (index, d) in enumerate(current_output_tmp) if d["name"] == focused_output), None)
        if not self.cache_grid:
            self.float_grid = self.calculate_grid(
                BASE_CONFIG["defaultGrid"]["rows"],
                BASE_CONFIG["defaultGrid"]["columns"],
                self.area_matrix[current_output_index],
            )
```

PS. Sorry for spamming the issue.

**Comment by justahuman1** [comment]
https://github.com/justahuman1/i3-grid/tree/v0.2.31 has this fix. I no longer run i3 so not sure if this works. I will test it one of these days and merge into master thanks

**Comment by laur89** [comment]
@justahuman1 please do not forget about this!

**Comment by justahuman1** [comment]
@laur89 Did the fix work? Should I merge into main?
